// AUTO-GENERATED by sim800-capabilities. DO NOT EDIT BY HAND.
// Source: data/models/*.yaml
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace sim800_capabilities {

enum class Family : std::uint8_t {
    SIM800 = 0,
    SIM808 = 1,
    SIM868 = 2,
};

enum class Status : std::uint8_t {
    documented = 0,
    not_documented = 1,
    not_supported = 2,
    inferred = 3,
    conflict = 4,
    not_in_scope = 5,
};

struct BandList {
    std::array<std::uint16_t, 4> values;
    std::uint8_t count;
    Status status;
};

struct FieldBool {
    bool value;
    Status status;
};

struct FieldInt {
    std::int32_t value;
    Status status;
};

struct FieldStr {
    std::string_view value;
    Status status;
};

struct Model {
    std::string_view name;
    Family family;
    BandList bands_gsm;
    BandList bands_gprs;
    FieldStr  band_type;
    FieldBool bluetooth_supported;
    FieldStr  bluetooth_version;
    FieldBool pcm_supported;
    FieldInt  pcm_channels;
    FieldStr  pcm_mode;
    FieldBool usb_supported;
    FieldStr  usb_version;
    FieldStr  usb_speed;
    FieldBool gnss_supported;
    FieldInt  gnss_channels;
    FieldStr  gnss_antenna_interface;
    FieldInt  gpio_count;
    FieldInt  adc_count;
    FieldInt  adc_resolution_bits;
    FieldInt  sim_count;
    FieldInt  uart_ports;
    FieldStr  uart_flow_control;
    FieldInt  vbat_min_mv;
    FieldInt  vbat_max_mv;
    FieldInt  operating_temperature_min_c;
    FieldInt  operating_temperature_max_c;
};

inline constexpr Model kModels[] = {
    Model{
        "SIM800", Family::SIM800,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {true, Status::documented},  // bluetooth_supported
        {"3.0", Status::documented},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {false, Status::not_supported}, // gnss_supported
        {0, Status::not_supported},   // gnss_channels
        {"", Status::not_supported},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM800A", Family::SIM800,
        {{900, 1800, 0, 0}, 2, Status::documented},   // bands_gsm
        {{900, 1800, 0, 0}, 2, Status::documented},  // bands_gprs
        {"dual-band", Status::documented},  // band_type
        {false, Status::not_supported},  // bluetooth_supported
        {"", Status::not_supported},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {false, Status::not_supported}, // gnss_supported
        {0, Status::not_supported},   // gnss_channels
        {"", Status::not_supported},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM800C", Family::SIM800,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {true, Status::documented},  // bluetooth_supported
        {"3.0", Status::documented},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {false, Status::not_supported}, // gnss_supported
        {0, Status::not_supported},   // gnss_channels
        {"", Status::not_supported},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM800C-DS", Family::SIM800,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {true, Status::documented},  // bluetooth_supported
        {"3.0", Status::documented},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {false, Status::not_supported}, // gnss_supported
        {0, Status::not_supported},   // gnss_channels
        {"", Status::not_supported},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {2, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM800F", Family::SIM800,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {true, Status::documented},  // bluetooth_supported
        {"3.0", Status::documented},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {false, Status::not_supported}, // gnss_supported
        {0, Status::not_supported},   // gnss_channels
        {"", Status::not_supported},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM800H", Family::SIM800,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {true, Status::documented},  // bluetooth_supported
        {"3.0", Status::documented},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {false, Status::not_supported}, // gnss_supported
        {0, Status::not_supported},   // gnss_channels
        {"", Status::not_supported},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM800L", Family::SIM800,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {false, Status::not_supported},  // bluetooth_supported
        {"", Status::not_supported},    // bluetooth_version
        {false, Status::not_supported},  // pcm_supported
        {0, Status::not_supported},    // pcm_channels
        {"", Status::not_supported},        // pcm_mode
        {false, Status::not_supported},  // usb_supported
        {"", Status::not_supported},     // usb_version
        {"", Status::not_supported},       // usb_speed
        {false, Status::not_supported}, // gnss_supported
        {0, Status::not_supported},   // gnss_channels
        {"", Status::not_supported},  // gnss_antenna_interface
        {3, Status::documented},      // gpio_count
        {1, Status::documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {1, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM808", Family::SIM808,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {false, Status::not_supported},  // bluetooth_supported
        {"", Status::not_supported},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {true, Status::documented}, // gnss_supported
        {22, Status::documented},   // gnss_channels
        {"active", Status::documented},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
    Model{
        "SIM868", Family::SIM868,
        {{850, 900, 1800, 1900}, 4, Status::documented},   // bands_gsm
        {{850, 900, 1800, 1900}, 4, Status::documented},  // bands_gprs
        {"quad-band", Status::documented},  // band_type
        {true, Status::documented},  // bluetooth_supported
        {"3.0", Status::documented},    // bluetooth_version
        {true, Status::documented},  // pcm_supported
        {2, Status::documented},    // pcm_channels
        {"both", Status::documented},        // pcm_mode
        {true, Status::documented},  // usb_supported
        {"2.0", Status::documented},     // usb_version
        {"full-speed", Status::documented},       // usb_speed
        {true, Status::documented}, // gnss_supported
        {22, Status::documented},   // gnss_channels
        {"active", Status::documented},  // gnss_antenna_interface
        {0, Status::not_documented},      // gpio_count
        {0, Status::not_documented},       // adc_count
        {0, Status::not_documented},  // adc_resolution_bits
        {1, Status::documented},       // sim_count
        {2, Status::documented},      // uart_ports
        {"hardware", Status::documented},  // uart_flow_control
        {3400, Status::documented},  // vbat_min_mv
        {4400, Status::documented},  // vbat_max_mv
        {-40, Status::documented},  // op_temp_min_c
        {85, Status::documented},  // op_temp_max_c
    },
};

inline constexpr std::size_t kModelCount = sizeof(kModels) / sizeof(kModels[0]);

}  // namespace sim800_capabilities
